---
title: "density_based"
output: html_document
date: "2024-07-18"
---

## Load library and dataset
```{r}
library(sf)
library(ggplot2)
library(spatstat)
library(nngeo)
library(tidyverse)

load(url("https://github.com/mgimond/Spatial/raw/main/Data/ppa.RData"))
```
```{r data prep}
marks(starbucks)  <- NULL
Window(starbucks) <- ma
plot(starbucks, main=NULL, cols=rgb(0,0,0,.2), pch=20)
hist(pop, main=NULL, las=1)
pop.lg <- log(pop)
hist(pop.lg, main=NULL, las=1)
```
```{r rescale}
starbucks.km <- rescale(starbucks, 1000, "km")
ma.km <- rescale(ma, 1000, "km")
pop.km    <- rescale(pop, 1000, "km")
pop.lg.km <- rescale(pop.lg, 1000, "km")
```

## Kernel density
```{r default bandwith}
#density function computes an isotropic kernel intensity estimate of the point patter, bandwith defines the kernel's window extent

K1 <- density(starbucks.km) # Using the default bandwidth
plot(K1, main=NULL, las=1)
contour(K1, add=TRUE)
```
```{r 50 km bandwith}
K2 <- density(starbucks.km, sigma=50) # Using a 50km bandwidth, length unit is extracted from point layer's map units
plot(K2, main=NULL, las=1)
contour(K2, add=TRUE)
#kernel defaults to gaussian smoothing function, can change to "quartic" "disc" or "epanechnikov" 
#ex - density(starbucks.km, kernel = "disc"...)
```

## Kernel density adjusted for covariate
```{r point process' intensity estimated following population density raster covariate}
rho <- rhohat(starbucks.km, pop.lg.km,  method="ratio") # Compute rho using the ratio method
plot(rho, las=1, main=NULL, legendargs=list(cex=0.8, xpd=TRUE, inset=c(1.01, 0) )) # Generate rho vs covariate plot
```

```{r map of predicated density if pop density were the sole driving process}
pred <- predict(rho)
cl   <- interp.colours(c("lightyellow", "orange" ,"red"), 100) # Create color scheme
plot(pred, col=cl, las=1, main=NULL, gamma = 0.25) # Gamma to stretch color scheme
```

```{r compare predicted vs observed intensity function}
K1_vs_pred <- pairs(K1, pred, plot = FALSE)
plot(K1_vs_pred$pred ~ K1_vs_pred$K1, pch=20,
     xlab = "Observed intensity", 
     ylab = "Predicted intensity", 
     col = rgb(0,0,0,0.1))
#if modeled intensity was comparable to observed intensity, points would cluster along a one-to-one diagonal

summary(as.data.frame(K1_vs_pred))
```

```{r limit data to observed intensities less than 0.04}
plot(K1_vs_pred$pred ~ K1_vs_pred$K1, pch=20,
     xlab = "Observed intensity", 
     ylab = "Predicted intensity", 
     col = rgb(0,0,0,0.1),
     xlim = c(0, 0.04), ylim = c(0, 0.1))
abline(a=0, b = 1, col = "red")
```

## Poisson point process
models relationship between predicted point pattern intensity and population density distribution
```{r creating model and plotting}
PPM1 <- ppm(starbucks.km ~ pop.lg.km)
plot(effectfun(PPM1, "pop.lg.km", se.fit=TRUE), main=NULL, 
     las=1, legendargs=list(cex=0.8, xpd=TRUE, inset=c(1.01, 0) ))
PPM1 #base intensity is close to 0 (e^-13.71) when logged pop density is zero, for every increase in 1 unit of logged pop density, starbucks point density increases by a factor of e^1.27 units
```