---
title: "distance_analysis"
author: "Margo Moceyunas"
date: "2024-07-16"
output: html_document
---
## Packages
```{r}
load(url("https://github.com/mgimond/Spatial/raw/main/Data/ppa.RData"))
library(spatstat)
library(sf)
```

## Data prep
```{r}
marks(starbucks)  <- NULL
Window(starbucks) <- ma
plot(starbucks, main=NULL, cols=rgb(0,0,0,.2), pch=20)
hist(pop, main=NULL, las=1)
pop.lg <- log(pop)
hist(pop.lg, main=NULL, las=1)
```

## Rescale
```{r}
starbucks.km <- rescale(starbucks, 1000, "km")
ma.km <- rescale(ma, 1000, "km")
pop.km    <- rescale(pop, 1000, "km")
pop.lg.km <- rescale(pop.lg, 1000, "km")
```

## Average nearest neighbor
```{r first and second nearest neibhor distance in km}
mean(nndist(starbucks.km, k=1))
mean(nndist(starbucks.km, k=2))
```

```{r ann vs neighbor order plot}
ANN <- apply(nndist(starbucks.km, k=1:100),2,FUN=mean)
plot(ANN ~ eval(1:100), type="b", main=NULL, las=1)
```

## Hypothesis test
```{r assuming uniform point density across the state}
ann.p <- mean(nndist(starbucks.km, k=1))
ann.p
```

```{r null model}
n     <- 599L               # Number of simulations
ann.r <- vector(length = n) # Create an empty object to be used to store simulated ANN values
for (i in 1:n){
  rand.p   <- rpoint(n=starbucks.km$n, win=ma.km)  # Generate random point locations
  ann.r[i] <- mean(nndist(rand.p, k=1))  # Tally the ANN values
}
plot(rand.p, pch=16, main=NULL, cols=rgb(0,0,0,0.5))
```

```{r expected values under the null}
hist(ann.r, main=NULL, las=1, breaks=40, col="bisque", xlim=range(ann.p, ann.r))
abline(v=ann.p, col="blue")
```

```{r control for influence due to population density distribution}
n     <- 599L
ann.r <- vector(length=n)
for (i in 1:n){
  rand.p   <- rpoint(n=starbucks.km$n, f=pop.km) 
  ann.r[i] <- mean(nndist(rand.p, k=1))
}
Window(rand.p) <- ma.km  # Replace raster mask with ma.km window
plot(rand.p, pch=16, main=NULL, cols=rgb(0,0,0,0.5))
hist(ann.r, main=NULL, las=1, breaks=40, col="bisque", xlim=range(ann.p, ann.r))
abline(v=ann.p, col="blue")
```

``` {r Computing pseudo p-value from simulation}
N.greater <- sum(ann.r > ann.p)
p <- min(N.greater + 1, n + 1 - N.greater) / (n +1)
p
```

## Test for poisson point process model with covariate effect
```{r}
PPM1 <- ppm(starbucks.km ~ pop.lg.km)
PPM1
PPM0 <- ppm(starbucks.km ~ 1)
PPM0
starbucks.km$n / area(ma.km) 
anova(PPM0, PPM1, test="LRT")

```


